### PR TITLE
Language Support: Simplified Chinese

### PR DESCRIPTION
**Pull request by WockyTheWolf**
Hi Moffein! I found ur RoR2 mod while I was surfing the internet and I just love it!!Thus I want to add a language support of Simplified Chinese to ur mod. I think it'll help more Chinese to know this mod better!

Cheers.

### CODE REVIEW

**Comment by Moffein** [comment]
Thanks!

**Comment by WockyTheWolf** [comment]
> Thanks!

It's my pleasure!! This translation is actually made by me and my bf JunJun soo I'm wondering if u can put both of our names in the contributor list, that'll be perfect~ Thanks again :D

**Comment by Moffein** [comment]
Sure thing! I've updated it on my end. He'll be listed the next time the mod updates on Thunderstore.

**Comment by WockyTheWolf** [comment]
Cool! That'll be nice! It's a pleasure to collaborate with u❤️

**Comment by Moffein** [comment]
When you get the chance, could you update "MOFFEIN_HAND_BODY_UTILITY_NEMESIS_DESC"?
It's been changed to "<style=cIsUtility>Boost</style>. Gain <style=cIsDamage>+50% damage</style> and <style=cIsUtility>50 armor</style>, but lose <style=cIsHealth>-30% movement speed</style>. Hit enemies to <style=cIsUtility>increase duration</style>."

**Comment by WockyTheWolf** [comment]
> When you get the chance, could you update "MOFFEIN_HAND_BODY_UTILITY_NEMESIS_DESC"?
> It's been changed to "<style=cIsUtility>Boost</style>. Gain <style=cIsDamage>+50% damage</style> and <style=cIsUtility>50 armor</style>, but lose <style=cIsHealth>-30% movement speed</style>. Hit enemies to <style=cIsUtility>increase duration</style>."

Sure! I'll get it done tonight.
Thanks for noticing us 😘

**Pull request merged**
