### PR TITLE
Language fr

### PR DESCRIPTION
**Pull request by Fyrebw**
Idk if I have to translate the name of the character himself too. And the copypasta was a pain, but normally you got now a french translation.

### CODE REVIEW

**Comment by Moffein** [comment]
Thanks!

**Comment by Moffein** [comment]
Could you translate MOFFEIN_HAND_BODY_SPECIAL_SPEED_DESC when you get the chance?

**Comment by Fyrebw** [comment]
Just saw that, I will look into it, no problem.

**Comment by Fyrebw** [comment]
[HAN-D.txt](https://github.com/Moffein/HAN-D_OVERCLOCKED/files/13462196/HAN-D.txt)
Here is the updated version, I forgot how github works also so idk if I should have done another pull request.

**Comment by Moffein** [comment]
This works, thanks.

**Pull request merged**
